export const Users = [
  {
    id: 1,
    profilePicture: "img/gee.jpeg",
    username: "Ola Ishola",
  },
  {
    id: 2,
    profilePicture: "img/ayo.jpeg",
    username: "Ayo Aderibigbe",
  },
  {
    id: 3,
    profilePicture: "img/lord.jpeg",
    username: "Lord Luggard",
  },
  {
    id: 4,
    profilePicture: "img/mrcool.jpeg",
    username: "Jack Dorsey",
  },
  {
    id: 5,
    profilePicture: "img/hoody.jpeg",
    username: "Kate Winterfell",
  },
  {
    id: 6,
    profilePicture: "img/swag.jpeg",
    username: "Tyrone Kelly",
  },
  {
    id: 7,
    profilePicture: "img/beauty.jpeg",
    username: "Danny Bennett",
  },
  {
    id: 8,
    profilePicture: "img/focus.jpeg",
    username: "Godwin Afolabi",
  },
  {
    id: 9,
    profilePicture: "img/mists.jpeg",
    username: "Fola Mekiota",
  },
  {
    id: 10,
    profilePicture: "img/smile.jpeg",
    username: "Sara Antweps",
  },

  {
    id: 11,
    profilePicture: "img/hat.jpeg",
    username: "Jimmy Handler",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Late Night coding with the Memphis group.",
    photo: "img/night.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "img/mobile.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "img/micon.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "img/mists.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "img/lord.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Just kopped this bad boy",
    photo: "img/maccy.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "img/smile.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "img/setup.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "img/solo.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Hacking the web with a stroke of code daily!!",
    photo: "img/hacker.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },

  {
    id: 11,
    desc: "Taking notes and writing psuedo code helps you to be a better dev!!",
    photo: "img/note.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
